install.packages("heterocop_0.1.0.0.tar.gz")
install.packages("shiny")
install.packages("corrplot")
install.packages("bslib")
install.packages("coulourpicker")
install.packages("shinyjs")
install.packages("ggplot2")
install.packages("mirai")

library(heterocop)
library(shiny)
library(igraph)
library(corrplot)
library(bslib)
library(colourpicker)
library(shinyjs)
library(ggplot2)
library(mirai)
